#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 0.1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "terraspace-bundler"
require "terraspace_bundler/cli"

TerraspaceBundler::CLI.start(ARGV)
